name: Deploy to Netlify

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "netlify-deploy"
  cancel-in-progress: false

jobs:
  Deploy-to-Netlify:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4 # Checkout the repository

      # Install Rust Nightly Toolchain, with Clippy & Rustfmt
      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Lint
        working-directory: ./frontend
        run: cargo clippy && cargo fmt

      # Install trunk
      - name: Download and install Trunk binary
        run: |
          wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.20.3/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - trunk
          sudo mv trunk /usr/local/bin/

      # Build the project using trunk
      - name: Build with Trunk
        working-directory: ./frontend
        run: trunk build --release

      # Set up Node.js to use Netlify CLI
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      # Install Netlify CLI globally using npm
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Deploy to Netlify using Netlify CLI
      - name: Deploy to Netlify
        working-directory: ./frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=dist --prod # Use the Netlify CLI command directly
